server:
  port: ${PORT:8086}
  
spring:
  application:
    name: ms-products
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors: ## CORS Configuration
        cors-configurations:
          '[/**]': ## For all routes
            allowedOrigins: ${ALLOWED_ORIGINS:*} # With '*' we allow all origins. We can restrict by indicating domains or ip + port, e.g. http://localhost:3000 (where our front is, or a Vercel domain)
            allowedHeaders: "*" ## All headers allowed
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH


## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
    
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}

logging:
  level:
    tracer: TRACE