server:
  port: ${PORT:8086}
  
spring:
  application:
    name: ms-products

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}
    
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}

logging:
  level:
    tracer: TRACE