server:
  port: ${PORT:8086}
  
spring:
  application:
    name: ms-products

## Eureka Server Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
    
elasticsearch:
  host: ${ELASTICSEARCH_HOST:unir-cluster-6455179952.us-east-1.bonsaisearch.net}
  credentials:
    user: ${ELASTICSEARCH_USER:evn3c7h37o}
    password: ${ELASTICSEARCH_PWD:9ofx819x28}
    