server:
  port: ${PORT:8086}
  
spring:
  application:
    name: ms-products

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
    
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}

logging:
  level:
    tracer: TRACE